[db_credentials]
username = "my_username"
password = "my_password"

[ftx]
ws_connection_url = "wss://ftx.com/ws/"
api_key_prod = "H2PipoMbv3XWHLcFD5qaOivJ4OCfJ4vOwEvTkcnr"
api_secret_prod = "KWXHIKVz6fCfyH71hHEr2AkYhgVR9dbwMHwPy5Ps"

[kite]

[fyers]

[google_sheets]
index_data = "https://docs.google.com/spreadsheets/d/1sYNIAlwalXSc8uF59hdxzAeGoXLQyzT-Xl-CtUZaglM/edit?usp=sharing"